# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 21:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=datetime.datetime(2016, 2, 25, 21, 41, 4, 830978, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
